config/routes.rb
# frozen_string_literal: true

Rails.application.routes.draw do
  match '(*any)',
        to: redirect(subdomain: ''),
        via: :all,
        constraints: ->(r) { r.subdomain.present? && r.subdomain == 'www' }

  root to: 'site#index'

  get '/signin', action: :new, controller: 'sessions', as: :sign_in
  delete '/signout', action: :destroy, controller: 'sessions', as: :sign_out
  get '/auth/github/callback', action: :create, controller: 'sessions'
  match '/auth/failure', to: 'sessions#failure', via: %i[get post delete]

  patch '/users/:id', to: 'users#update', as: :user
  delete '/users/:id', action: :destroy, controller: 'users'

  get '/settings', action: :index, controller: 'settings'

  get '/privacy', to: 'site#privacy'

  get 'staff', to: 'staff#index'
  require 'sidekiq/web'
  constraints ->(request) { StaffController.staff_request?(request) } do
    mount Sidekiq::Web => 'staff/sidekiq'
  end

  mount Flipper::Cloud.app, at: 'webhooks/flipper'

  match '*unmatched_route', to: 'application#render404', via: :all
end

app/views/partials/_footer.html.erb
<footer class="pv4 ph3 ph5-m ph6-l">
  <div class="tc mt3">
    <a href="/" title="Home" class="f6 dib ph2 link moon-gray dim">Home</a>
    <a href="https://github.com/gjtorikian/past.codes" title="Source" class="f6 dib ph2 link moon-gray dim">Source</a>
    <a href="/privacy"  title="Privacy" class="f6 dib ph2 link moon-gray dim">Privacy</a>
  </div>
</footer>

app/views/partials/_masthead.html.erb
<nav class="dt w-100 border-box pa3 ph5-ns pb5">
  <div class="dtc v-mid w-75 tr">
    <% if !signed_in? %>
      <a href="<%= sign_in_path %>" title="Sign in to GitHub" class="no-underline f6 link dim br3 ph3 pv2 mb2 dib white bg-blue inline-flex items-center">
        <svg class="dib h2 w2" fill="#ffffff" xmlns="http://www.w3.org/2000/svg" viewBox="0 0 16 16" fill-rule="evenodd" clip-rule="evenodd" stroke-linejoin="round" stroke-miterlimit="1.414"><path d="M8 0C3.58 0 0 3.582 0 8c0 3.535 2.292 6.533 5.47 7.59.4.075.547-.172.547-.385 0-.19-.007-.693-.01-1.36-2.226.483-2.695-1.073-2.695-1.073-.364-.924-.89-1.17-.89-1.17-.725-.496.056-.486.056-.486.803.056 1.225.824 1.225.824.714 1.223 1.873.87 2.33.665.072-.517.278-.87.507-1.07-1.777-.2-3.644-.888-3.644-3.953 0-.873.31-1.587.823-2.147-.083-.202-.358-1.015.077-2.117 0 0 .672-.215 2.2.82.638-.178 1.323-.266 2.003-.27.68.004 1.364.092 2.003.27 1.527-1.035 2.198-.82 2.198-.82.437 1.102.163 1.915.08 2.117.513.56.823 1.274.823 2.147 0 3.073-1.87 3.75-3.653 3.947.287.246.543.735.543 1.48 0 1.07-.01 1.933-.01 2.195 0 .215.144.463.55.385C13.71 14.53 16 11.534 16 8c0-4.418-3.582-8-8-8"/></svg>
        <span class="f6 ml3 pr2">Sign in</span>
      </a>
    <% else %>
      <a href="/settings" title="Settings" class="no-underline f6 link dim br3 ph3 pv2 mb2 dib white bg-blue inline-flex items-center">
        <svg class="dib h2 w2" fill="#ffffff" xmlns="http://www.w3.org/2000/svg" viewBox="0 0 24 24" width="24" height="24"><path fill-rule="evenodd" d="M7.875 2.292a.125.125 0 00-.032.018A7.24 7.24 0 004.75 8.25a7.247 7.247 0 003.654 6.297c.57.327.982.955.941 1.682v.002l-.317 6.058a.75.75 0 11-1.498-.078l.317-6.062v-.004c.006-.09-.047-.215-.188-.296A8.747 8.747 0 013.25 8.25a8.74 8.74 0 013.732-7.169 1.547 1.547 0 011.709-.064c.484.292.809.835.809 1.46v4.714a.25.25 0 00.119.213l2.25 1.385c.08.05.182.05.262 0l2.25-1.385a.25.25 0 00.119-.213V2.478c0-.626.325-1.169.81-1.461a1.547 1.547 0 011.708.064 8.74 8.74 0 013.732 7.17 8.747 8.747 0 01-4.41 7.598c-.14.081-.193.206-.188.296v.004l.318 6.062a.75.75 0 11-1.498.078l-.317-6.058v-.002c-.041-.727.37-1.355.94-1.682A7.247 7.247 0 0019.25 8.25a7.24 7.24 0 00-3.093-5.94.125.125 0 00-.032-.018l-.01-.001c-.003 0-.014 0-.031.01-.036.022-.084.079-.084.177V7.19a1.75 1.75 0 01-.833 1.49l-2.25 1.385a1.75 1.75 0 01-1.834 0l-2.25-1.384A1.75 1.75 0 018 7.192V2.477c0-.098-.048-.155-.084-.176a.062.062 0 00-.031-.011l-.01.001z"></path></svg>
        <span class="f6 ml3 pr2">Settings</span>
      </a>
      <a href="<%= sign_out_path %>" data-method="delete" title="Signout" class="no-underline f6 link dim br3 ph3 pv2 mb2 dib white bg-blue inline-flex items-center">
        <svg class="dib h2 w2" fill="#ffffff" xmlns="http://www.w3.org/2000/svg" viewBox="0 0 24 24" width="24" height="24"><path fill-rule="evenodd" d="M3 3.25c0-.966.784-1.75 1.75-1.75h5.5a.75.75 0 010 1.5h-5.5a.25.25 0 00-.25.25v17.5c0 .138.112.25.25.25h5.5a.75.75 0 010 1.5h-5.5A1.75 1.75 0 013 20.75V3.25zm16.006 9.5l-3.3 3.484a.75.75 0 001.088 1.032l4.5-4.75a.75.75 0 000-1.032l-4.5-4.75a.75.75 0 00-1.088 1.032l3.3 3.484H10.75a.75.75 0 000 1.5h8.256z"></path></svg>
        <span class="f6 ml3 pr2">Signout</span>
      </a>
    <% end %>
  </div>
</nav>